name: Tests
on: push
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build wasm files
        run: cd scripts && chmod +x build.sh && ./build.sh 
      - name: Run unit tests
        env:
          IS_GITHUB_ACTION: true
        run: cd scripts && chmod +x unit_tests.sh && ./unit_tests.sh
      - name: Run integration tests
        run: cd scripts && chmod +x integration_tests.sh && ./integration_tests.sh